"""Deterministic, readable scalar C generation for the RGBA8 pixel IR."""

from __future__ import annotations

from dataclasses import dataclass
import struct

from .ir import Operation, PixelIR
from .passes import PassResult, optimize_ir


@dataclass(frozen=True)
class GeneratedC:
    source: str
    plan_hash: str
    optimized_plan_hash: str
    passes: PassResult


def _f32(value: float) -> float:
    return struct.unpack("=f", struct.pack("=f", value))[0]


def _u8(value: int) -> int:
    return max(0, min(255, value))


def _format_table(
    name: str, c_type: str, rows: tuple[tuple[int, ...], ...]
) -> list[str]:
    lines = [f"static const {c_type} {name}[{len(rows)}][256] = {{"]
    for row in rows:
        lines.append("    {")
        for start in range(0, 256, 16):
            values = ", ".join(str(value) for value in row[start : start + 16])
            lines.append(f"        {values},")
        lines.append("    },")
    lines.append("};")
    return lines


def _levels_tables(operation: Operation) -> tuple[tuple[int, ...], ...]:
    parameters = operation.parameters
    output: list[tuple[int, ...]] = []
    for channel in range(4):
        coefficient = _f32(float.fromhex(parameters["coefficients"][channel][channel]))
        input_offset = parameters["offsets"][channel]["input"]
        output_offset = parameters["offsets"][channel]["output"]
        output.append(
            tuple(
                _u8(
                    int(
                        _f32(
                            (value - input_offset) * coefficient + output_offset
                        )
                    )
                )
                for value in range(256)
            )
        )
    return tuple(output)


def _stage_declarations(stages: list[Operation]) -> list[str]:
    lines: list[str] = []
    for index, operation in enumerate(stages):
        if operation.kind == "lut8":
            lines.append(f"/* stage {index}: four independent byte lookup tables */")
            rows = tuple(tuple(row) for row in operation.parameters["tables"])
            lines.extend(_format_table(f"lut_{index}", "uint8_t", rows))
        elif operation.parameters["evaluation"] == "levels_f32_fma":
            lines.append(
                f"/* stage {index}: materialized levels_f32_fma (single-rounding oracle) */"
            )
            lines.extend(
                _format_table(f"levels_{index}", "uint8_t", _levels_tables(operation))
            )
        else:
            lines.append(
                f"/* stage {index}: independently ties-to-even-rounded mixer terms */"
            )
            rows = tuple(
                tuple(table)
                for output_row in operation.parameters["contribution_tables"]
                for table in output_row
            )
            lines.extend(_format_table(f"mixer_{index}", "int16_t", rows))
        lines.append("")
    return lines


def _stage_body(index: int, operation: Operation) -> list[str]:
    if operation.kind == "lut8":
        return [
            f"            c{channel} = lut_{index}[{channel}][c{channel}];"
            for channel in range(4)
        ]
    if operation.parameters["evaluation"] == "levels_f32_fma":
        return [
            f"            c{channel} = levels_{index}[{channel}][c{channel}];"
            for channel in range(4)
        ]

    lines = []
    for output in range(4):
        terms = " + ".join(
            f"mixer_{index}[{output * 4 + input_}][c{input_}]"
            for input_ in range(4)
        )
        lines.append(f"            int32_t n{index}_{output} = {terms};")
    lines.extend(
        f"            c{channel} = lavfi_saturate_i32(n{index}_{channel});"
        for channel in range(4)
    )
    return lines


def generate_c(
    ir: PixelIR,
    *,
    identity_elimination: bool = True,
    lut_composition: bool = True,
) -> GeneratedC:
    """Generate one C translation unit exporting the versioned kernel ABI."""

    passes = optimize_ir(
        ir,
        identity_elimination=identity_elimination,
        lut_composition=lut_composition,
    )
    body = passes.ir.operations[1:-1]
    stages = [body[index] for index in range(0, len(body), 2)]
    uses_mixer = any(
        operation.kind == "matrix4x4"
        and operation.parameters["evaluation"]
        == "sum_i32_terms_rounded_ties_even"
        for operation in stages
    )

    lines = [
        "/* Generated by lavfi-cc. This file is deterministic for its input IR. */",
        f"/* source plan: {ir.plan_hash} */",
        f"/* optimized plan: {passes.ir.plan_hash} */",
        '#include "kernel_abi.h"',
        "",
    ]
    if uses_mixer:
        lines.extend(
            [
                "static inline uint8_t lavfi_saturate_i32(int32_t value)",
                "{",
                "    if (value < 0)",
                "        return 0;",
                "    if (value > 255)",
                "        return 255;",
                "    return (uint8_t)value;",
                "}",
                "",
            ]
        )
    lines.extend(_stage_declarations(stages))
    lines.extend(
        [
            "static void process_rgba8(",
            "    uint8_t *dst, ptrdiff_t dst_stride,",
            "    const uint8_t *src, ptrdiff_t src_stride,",
            "    int width, int height)",
            "{",
            "    for (int y = 0; y < height; ++y) {",
            "        const uint8_t *source_row = src + (ptrdiff_t)y * src_stride;",
            "        uint8_t *destination_row = dst + (ptrdiff_t)y * dst_stride;",
            "        for (int x = 0; x < width; ++x) {",
            "            const uint8_t *source = source_row + (ptrdiff_t)x * 4;",
            "            uint8_t *destination = destination_row + (ptrdiff_t)x * 4;",
            "            uint8_t c0 = source[0];",
            "            uint8_t c1 = source[1];",
            "            uint8_t c2 = source[2];",
            "            uint8_t c3 = source[3];",
        ]
    )
    for index, operation in enumerate(stages):
        lines.append("")
        lines.append(f"            /* stage {index} */")
        lines.extend(_stage_body(index, operation))
    lines.extend(
        [
            "",
            "            destination[0] = c0;",
            "            destination[1] = c1;",
            "            destination[2] = c2;",
            "            destination[3] = c3;",
            "        }",
            "    }",
            "}",
            "",
            f'static const char kernel_plan_hash[] = "{ir.plan_hash}";',
            "",
            "LAVFI_KERNEL_EXPORT const LavfiCompiledKernel lavfi_compiled_kernel = {",
            "    LAVFI_KERNEL_ABI_VERSION,",
            "    LAVFI_PIXEL_FORMAT_RGBA8,",
            "    kernel_plan_hash,",
            "    process_rgba8,",
            "};",
            "",
        ]
    )
    return GeneratedC(
        "\n".join(lines),
        ir.plan_hash,
        passes.ir.plan_hash,
        passes,
    )
